name: Gitea Actions Demo
run-name: ${{ gitea.actor }} is testing out Gitea Actions 🚀
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 2 * * *' 

jobs:
  Explore-Gitea-Actions:
    runs-on: ubuntu-latest
    env:
      ENV_NAME: production
    strategy:
      matrix:
        python-version: [ "3.9", "3.10", "3.11" ]
        #os: [ubuntu-latest, linux]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          PYTHONPATH=. pytest --html=report_${{ matrix.python-version }}.html --self-contained-html --maxfail=1 --disable-warnings -q

      - name: Upload report as package
        uses: actions/upload-artifact@v3
        with:
          name: pytest-report
          path: report_${{ matrix.python-version }}.html


  # Linting Job
  lint:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up virtual environment
        run: python3 -m venv venv

      - name: Install flake8
        run: |
          source venv/bin/activate
          pip install flake8
          flake8 . --statistics
